name: Deployment
on: 
    push: 
        branches: 
            - main
            - dev
env:
    MONGODB_DB_NAME: gha-demo
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            MONGODB_USERNAME: faranbutt789
            MONGODB_PASSWORD: n4W3cIhf3oQYknID 
            MONGODB_CLUSTER_ADDRESS: cluster0.rvdrrpz.mongodb.net
            PORT: 3000
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: npm-deps-${{hashFiles('**/package-lock.json')}}
            - name: Install dependencies
              uses: npm ci
            - name: Run server
              run: npm start and npx wait-on http://127.0.0.1:$PORT
            - name: testing
              run: npm test
            - name: Output Information
              run: echo "MONGODB_USERNAME = ${{ env.MONGODB_USERNAME }}"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: |
                echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME}}"
                echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
